# Form implementation generated from reading ui file 'QtLoggerConfigurationGeneratedGUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_QtLoggerConfigurationGenerated(object):
    def setupUi(self, QtLoggerConfigurationGenerated):
        QtLoggerConfigurationGenerated.setObjectName("QtLoggerConfigurationGenerated")
        QtLoggerConfigurationGenerated.resize(611, 470)
        self.loggerValidateConf = QtWidgets.QDialogButtonBox(parent=QtLoggerConfigurationGenerated)
        self.loggerValidateConf.setGeometry(QtCore.QRect(510, 10, 81, 241))
        self.loggerValidateConf.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.loggerValidateConf.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.loggerValidateConf.setObjectName("loggerValidateConf")
        self.loggerPlainTextEdit = QtWidgets.QPlainTextEdit(parent=QtLoggerConfigurationGenerated)
        self.loggerPlainTextEdit.setGeometry(QtCore.QRect(10, 10, 491, 441))
        self.loggerPlainTextEdit.setObjectName("loggerPlainTextEdit")

        self.retranslateUi(QtLoggerConfigurationGenerated)
        self.loggerValidateConf.accepted.connect(QtLoggerConfigurationGenerated.accept) # type: ignore
        self.loggerValidateConf.rejected.connect(QtLoggerConfigurationGenerated.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(QtLoggerConfigurationGenerated)

    def retranslateUi(self, QtLoggerConfigurationGenerated):
        _translate = QtCore.QCoreApplication.translate
        QtLoggerConfigurationGenerated.setWindowTitle(_translate("QtLoggerConfigurationGenerated", "Dialog"))
